spring.application.name=SistemaDeReclutamiento
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.downckrdepwwtewuchnl
spring.datasource.password=TF8D111CD207C

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration